#pragma once

typedef int input_code_t;

/* Printable keys */
constexpr input_code_t AP_KEY_SPACE              = 32;
constexpr input_code_t AP_KEY_APOSTROPHE         = 39;  /* ' */
constexpr input_code_t AP_KEY_COMMA              = 44;  /* , */
constexpr input_code_t AP_KEY_MINUS              = 45;  /* - */
constexpr input_code_t AP_KEY_PERIOD             = 46;  /* . */
constexpr input_code_t AP_KEY_SLASH              = 47;  /* / */
constexpr input_code_t AP_KEY_0                  = 48;
constexpr input_code_t AP_KEY_1                  = 49;
constexpr input_code_t AP_KEY_2                  = 50;
constexpr input_code_t AP_KEY_3                  = 51;
constexpr input_code_t AP_KEY_4                  = 52;
constexpr input_code_t AP_KEY_5                  = 53;
constexpr input_code_t AP_KEY_6                  = 54;
constexpr input_code_t AP_KEY_7                  = 55;
constexpr input_code_t AP_KEY_8                  = 56;
constexpr input_code_t AP_KEY_9                  = 57;
constexpr input_code_t AP_KEY_SEMICOLON          = 59;  /* ; */
constexpr input_code_t AP_KEY_EQUAL              = 61;  /* = */
constexpr input_code_t AP_KEY_A                  = 65;
constexpr input_code_t AP_KEY_B                  = 66;
constexpr input_code_t AP_KEY_C                  = 67;
constexpr input_code_t AP_KEY_D                  = 68;
constexpr input_code_t AP_KEY_E                  = 69;
constexpr input_code_t AP_KEY_F                  = 70;
constexpr input_code_t AP_KEY_G                  = 71;
constexpr input_code_t AP_KEY_H                  = 72;
constexpr input_code_t AP_KEY_I                  = 73;
constexpr input_code_t AP_KEY_J                  = 74;
constexpr input_code_t AP_KEY_K                  = 75;
constexpr input_code_t AP_KEY_L                  = 76;
constexpr input_code_t AP_KEY_M                  = 77;
constexpr input_code_t AP_KEY_N                  = 78;
constexpr input_code_t AP_KEY_O                  = 79;
constexpr input_code_t AP_KEY_P                  = 80;
constexpr input_code_t AP_KEY_Q                  = 81;
constexpr input_code_t AP_KEY_R                  = 82;
constexpr input_code_t AP_KEY_S                  = 83;
constexpr input_code_t AP_KEY_T                  = 84;
constexpr input_code_t AP_KEY_U                  = 85;
constexpr input_code_t AP_KEY_V                  = 86;
constexpr input_code_t AP_KEY_W                  = 87;
constexpr input_code_t AP_KEY_X                  = 88;
constexpr input_code_t AP_KEY_Y                  = 89;
constexpr input_code_t AP_KEY_Z                  = 90;
constexpr input_code_t AP_KEY_LEFT_BRACKET       = 91;  /* [ */
constexpr input_code_t AP_KEY_BACKSLASH          = 92;  /* \ */
constexpr input_code_t AP_KEY_RIGHT_BRACKET      = 93;  /* ] */
constexpr input_code_t AP_KEY_GRAVE_ACCENT       = 96;  /* ` */
constexpr input_code_t AP_KEY_WORLD_1            = 161; /* non-US #1 */
constexpr input_code_t AP_KEY_WORLD_2            = 162; /* non-US #2 */
												  
/* Function keys */								 
constexpr input_code_t AP_KEY_ESCAPE             = 256;
constexpr input_code_t AP_KEY_ENTER              = 257;
constexpr input_code_t AP_KEY_TAB                = 258;
constexpr input_code_t AP_KEY_BACKSPACE          = 259;
constexpr input_code_t AP_KEY_INSERT             = 260;
constexpr input_code_t AP_KEY_DELETE             = 261;
constexpr input_code_t AP_KEY_RIGHT              = 262;
constexpr input_code_t AP_KEY_LEFT               = 263;
constexpr input_code_t AP_KEY_DOWN               = 264;
constexpr input_code_t AP_KEY_UP                 = 265;
constexpr input_code_t AP_KEY_PAGE_UP            = 266;
constexpr input_code_t AP_KEY_PAGE_DOWN          = 267;
constexpr input_code_t AP_KEY_HOME               = 268;
constexpr input_code_t AP_KEY_END                = 269;
constexpr input_code_t AP_KEY_CAPS_LOCK          = 280;
constexpr input_code_t AP_KEY_SCROLL_LOCK        = 281;
constexpr input_code_t AP_KEY_NUM_LOCK           = 282;
constexpr input_code_t AP_KEY_PRINT_SCREEN       = 283;
constexpr input_code_t AP_KEY_PAUSE              = 284;
constexpr input_code_t AP_KEY_F1                 = 290;
constexpr input_code_t AP_KEY_F2                 = 291;
constexpr input_code_t AP_KEY_F3                 = 292;
constexpr input_code_t AP_KEY_F4                 = 293;
constexpr input_code_t AP_KEY_F5                 = 294;
constexpr input_code_t AP_KEY_F6                 = 295;
constexpr input_code_t AP_KEY_F7                 = 296;
constexpr input_code_t AP_KEY_F8                 = 297;
constexpr input_code_t AP_KEY_F9                 = 298;
constexpr input_code_t AP_KEY_F10                = 299;
constexpr input_code_t AP_KEY_F11                = 300;
constexpr input_code_t AP_KEY_F12                = 301;
constexpr input_code_t AP_KEY_F13                = 302;
constexpr input_code_t AP_KEY_F14                = 303;
constexpr input_code_t AP_KEY_F15                = 304;
constexpr input_code_t AP_KEY_F16                = 305;
constexpr input_code_t AP_KEY_F17                = 306;
constexpr input_code_t AP_KEY_F18                = 307;
constexpr input_code_t AP_KEY_F19                = 308;
constexpr input_code_t AP_KEY_F20                = 309;
constexpr input_code_t AP_KEY_F21                = 310;
constexpr input_code_t AP_KEY_F22                = 311;
constexpr input_code_t AP_KEY_F23                = 312;
constexpr input_code_t AP_KEY_F24                = 313;
constexpr input_code_t AP_KEY_F25                = 314;
constexpr input_code_t AP_KEY_KP_0               = 320;
constexpr input_code_t AP_KEY_KP_1               = 321;
constexpr input_code_t AP_KEY_KP_2               = 322;
constexpr input_code_t AP_KEY_KP_3               = 323;
constexpr input_code_t AP_KEY_KP_4               = 324;
constexpr input_code_t AP_KEY_KP_5               = 325;
constexpr input_code_t AP_KEY_KP_6               = 326;
constexpr input_code_t AP_KEY_KP_7               = 327;
constexpr input_code_t AP_KEY_KP_8               = 328;
constexpr input_code_t AP_KEY_KP_9               = 329;
constexpr input_code_t AP_KEY_KP_DECIMAL         = 330;
constexpr input_code_t AP_KEY_KP_DIVIDE          = 331;
constexpr input_code_t AP_KEY_KP_MULTIPLY        = 332;
constexpr input_code_t AP_KEY_KP_SUBTRACT        = 333;
constexpr input_code_t AP_KEY_KP_ADD             = 334;
constexpr input_code_t AP_KEY_KP_ENTER           = 335;
constexpr input_code_t AP_KEY_KP_EQUAL           = 336;
constexpr input_code_t AP_KEY_LEFT_SHIFT         = 340;
constexpr input_code_t AP_KEY_LEFT_CONTROL       = 341;
constexpr input_code_t AP_KEY_LEFT_ALT           = 342;
constexpr input_code_t AP_KEY_LEFT_SUPER         = 343;
constexpr input_code_t AP_KEY_RIGHT_SHIFT        = 344;
constexpr input_code_t AP_KEY_RIGHT_CONTROL      = 345;
constexpr input_code_t AP_KEY_RIGHT_ALT          = 346;
constexpr input_code_t AP_KEY_RIGHT_SUPER        = 347;
constexpr input_code_t AP_KEY_MENU               = 348;
												 
constexpr input_code_t AP_MOUSE_BUTTON_1         = 0;
constexpr input_code_t AP_MOUSE_BUTTON_2         = 1;
constexpr input_code_t AP_MOUSE_BUTTON_3         = 2;
constexpr input_code_t AP_MOUSE_BUTTON_4         = 3;
constexpr input_code_t AP_MOUSE_BUTTON_5         = 4;
constexpr input_code_t AP_MOUSE_BUTTON_6         = 5;
constexpr input_code_t AP_MOUSE_BUTTON_7         = 6;
constexpr input_code_t AP_MOUSE_BUTTON_8         = 7;
constexpr input_code_t AP_MOUSE_BUTTON_LEFT      = AP_MOUSE_BUTTON_1;
constexpr input_code_t AP_MOUSE_BUTTON_RIGHT     = AP_MOUSE_BUTTON_2;
constexpr input_code_t AP_MOUSE_BUTTON_MIDDLE    = AP_MOUSE_BUTTON_3;

constexpr input_code_t AP_LAST_KEY               = AP_KEY_MENU;